import handibadgnath from "../img/blogs/sample.jpg";

const BlogsData = [
  {
    id: 1,
    image: handibadgnath,
    title: "Handibadgnath Sunset",
    link: "https://www.instagram.com/weekendworld/",
    date: 21,
    month: "Mar",
    year: 2020,
  },
  {
    id: 2,
    image: handibadgnath,
    title: "Handibadgnath Sunset",
    link: "https://www.instagram.com/weekendworld/",
    date: 21,
    month: "Mar",
    year: 2020,
  },
  {
    id: 3,
    image: handibadgnath,
    title: "Handibadgnath Sunset",
    link: "https://www.instagram.com/weekendworld/",
    date: 21,
    month: "Mar",
    year: 2020,
  },
  {
    id: 4,
    image: handibadgnath,
    title: "Handibadgnath Sunset",
    link: "https://www.instagram.com/weekendworld/",
    date: 21,
    month: "Mar",
    year: 2020,
  },
  {
    id: 5,
    image: handibadgnath,
    title: "Handibadgnath Sunset",
    link: "https://www.instagram.com/weekendworld/",
    date: 21,
    month: "Mar",
    year: 2020,
  },
  {
    id: 6,
    image: handibadgnath,
    title: "Handibadgnath Sunset",
    link: "https://www.instagram.com/weekendworld/",
    date: 21,
    month: "Mar",
    year: 2020,
  },
  {
    id: 7,
    image: handibadgnath,
    title: "Handibadgnath Sunset",
    link: "https://www.instagram.com/weekendworld/",
    date: 21,
    month: "Mar",
    year: 2020,
  },
  {
    id: 8,
    image: handibadgnath,
    title: "Handibadgnath Sunset",
    link: "https://www.instagram.com/weekendworld/",
    date: 21,
    month: "Mar",
    year: 2020,
  },
];

export default BlogsData;
